// assets/js/components/entry-modal.jsx
import axios from "axios";
import React from "react";
import Modal from "components/modal";
import InputDate from "components/entryModal/input-date";
import InputItemAndAmount from "components/entryModal/input-item-and-amount";

export default React.createClass({
  // API
  open(transaction) {
    transaction = transaction || { date: new Date(), entries: [{id: "debit_0", side_id: 1, amount: 0}, {id: "credit_0", side_id: 2, amount: 0}] };
    this.setState({
      id: transaction.id,
      date: new Date(transaction.date).toISOString().substring(0, 10),
      debits:  _(transaction.entries).filter((one) => one.side_id === 1).cloneDeep(),
      credits: _(transaction.entries).filter((one) => one.side_id === 2).cloneDeep(),
      show: true
    });
  },
  close() {
    this.setState({ show: false });
  },
  // handlers
  handleCancel(e) {
    e.preventDefault();
    this.close();
  },
  handleSubmit(e) {
    e.preventDefault();
    // todo validate
    axios.post(this.props.url, {
      transaction: {
        date: new Date(this.state.date).toISOString(),
        entries: _(this.state.debits.concat(this.state.credits)).filter((one) => one.item && one.item.id && one.amount).value()
      }
    }).then((data) => {
      this.props.onSave(data.data.data);
    }).catch((xhr, status, err) => {
      console.error(this.props.url, status, (err || "").toString());
    });
  },
  handleChangeDate() {
    var newVal = Date.parse(this.refs.date.value());
    if (newVal) this.setState({ date: new Date(newVal).toISOString().substring(0, 10) });
  },
  handleChangeDebit(data) {
    _.extend(_.find(this.state.debits, { id: data.id }), data);
    this.setState({ debits: this.state.debits });
    // if (_.last(this.state.debits).amount) {
    //   this.setState({ debits: this.state.debits.concat({ id: "debit" + this.state.debits.length, item_id: null, amount: null, side_id: 1 }) });
    // } else {
    //   this.setState({ debits: this.state.debits });
    // }
  },
  handleChangeCredit(data) {
    _.extend(_.find(this.state.credits, { id: data.id }), data);
    this.setState({ credits: this.state.credits });
    // if (_.last(this.state.credits).amount) {
    //   this.setState({ credits: newCredits.concat({ id: "credit" + newCredits.length, item_id: null, amount: null, side_id: 2 }) });
    // } else {
    //   this.setState({ credits: newCredits });
    // }
  },
  render() {
    if (!this.state || !this.state.show) return (<div />);

    var debits = this.state.debits.map((one) => {
      return (<InputItemAndAmount key={one.id} items={this.props.items} data={one} onChange={this.handleChangeDebit}/>);
    });
    var credits = this.state.credits.map((one) => {
      return (<InputItemAndAmount key={one.id} items={this.props.items} data={one} onChange={this.handleChangeCredit}/>);
    });

    return (
      <Modal>
        <form className="form" onSubmit={this.handleSubmit}>
          <Modal.Header onHide={this.handleCancel}>
            <h4>{this.props.title}</h4>
          </Modal.Header>

          <Modal.Body>
            <div className="form-group">
              <InputDate value={this.state.date} onChange={this.handleChangeDate} ref="date"/>
            </div>

            <legend>借方</legend>
            <div className="form-group">{debits}</div>

            <legend>貸方</legend>
            <div className="form-group">{credits}</div>
          </Modal.Body>

          <Modal.Footer>
            <button type="button" className="btn btn-default" onClick={this.handleCancel}>キャンセル</button>
            <button type="submit" className="btn btn-primary">OK</button>
          </Modal.Footer>
        </form>
      </Modal>
    );
  }
});

// assets/js/components/templates/EntryModal.vue
<template>
<md-dialog :md-active.sync="isShow" md-fullscreen="false">
  <md-dialog-title>{{title}}</md-dialog-title>

  <md-datepicker v-model="date" />

  <entry-side-form title="借方" v-model="debits" :items="items"/>

  <entry-side-form title="貸方" v-model="credits" :items="items"/>

  <md-field>
    <label>備考</label>
    <md-textarea v-model="description" md-autogrow></md-textarea>
  </md-field>

  <md-dialog-actions>
    <md-button class="" @click="close">キャンセル</md-button>
    <md-button class="md-primary" @click="submit">登録</md-button>
  </md-dialog-actions>
</md-dialog>
</template>

<script>
import EntrySideForm from '@/components/organisms/EntrySideForm';
import moment from 'moment';
import axios from "axios";

export default {
  name: 'EntryModal',
  components: { EntrySideForm },
  props: {
    title: String,
    items: Array
  },
  data: () => ({
    isShow: false,
    id: null,
    date: null,
    debits:  [{item_id: null, amount: null}],
    credits: [{item_id: null, amount: null}],
    description: ""
  }),
  methods: {
    /**
     * このモーダルを表示します
     */
    open: function(transaction) {
      this.isShow = true;
      if (transaction) {
        this.id = transaction.id;
        this.date = transaction.date;
        this.debits = (transaction.entries || []).filter((entry) => entry.side_id === 2).map((e) => ({
          id: e.id,
          item_id: e.item.id,
          amount: e.amount,
        }));
        this.credits = (transaction.entries || []).filter((entry) => entry.side_id === 1).map((e) => ({
          id: e.id,
          item_id: e.item.id,
          amount: e.amount,
        }));
        this.description = transaction.description;
      } else {
        this.id = null;
        this.date = null;
        this.debits = [{item_id: null, amount: null}];
        this.credits = [{item_id: null, amount: null}];
        this.description = "";
      }
    },
    /**
     * このモーダルを除去します
     */
    close: function() {
      // TODO 入力がある場合に確認を行う
      this.isShow = false;
    },
    /**
     * このモーダルの入力内容を登録します
     */
    submit: function() {
      let data = {
        transaction: {
          id: this.id,
          date: this.date,
          entries: ([]).concat(
            this.debits.map((e) => ({side_id: 1, item_id: e.item_id, amount: e.amount})),
            this.credits.map((e) => ({side_id: 2, item_id: e.item_id, amount: e.amount})),
          ),
          description: this.description,
        }
      };

      if (this.id) {
        axios.put(`api/transactions/${this.id}`, data);
      } else {
        axios.post('api/transactions', data);
      }
    }
  }
}
</script>
